title = "ARCropolis update: Ver. 3.11.0"
date = "12/01/2022"
description = "Thank you for updating to the latest version of ARCropolis.<br/>Please read the following changelog."

[[entries]]
section_title = "New feature(s)"
contents = """
<ul>
    <li>New option to skip the title screen in the configuration editor menu (by Raytwo/jozz)</li>
    <li>New option to force displaying folder names for the mod manager in the configuration editor menu (by jozz)</li>
</ul>"""

[[entries]]
section_title = "Bug fix(es)"
contents = """
<ul>
    <li>Starting the game with a Switch account that doesn't a save file will not crash anymore</li>
    <li>Restore loading times back to how they were on version 3.9.0</li>
</ul>"""

[[entries]]
section_title = "Improvement(s)"
contents = """
<ul>
    <li>The message about unsupported discovery methods has been slightly tweaked</li>
</ul>"""

[[entries]]
section_title = "Note(s)"
contents = """
<ul>
    <li>ARCropolis is now considered feature complete. Expect mostly bugfixes and QoL improvements from now on.</li>
</ul>"""