title = "ARCropolis update: Ver. 3.6.2"
date = "08/08/2022"
description = "Thank you for updating to the latest version of ARCropolis.<br/>Please read the following changelog."

[[entries]]
section_title = "Bug fixe(s)"
contents = """
<ul>
    <li>Fix share-to-vanilla in config.json</li>
    <li>Fix infinite loadings</li>
</ul>"""

[[entries]]
section_title = "Note(s)"
contents = """
<ul>
    <li>ARCropolis is now considered feature complete. Expect mostly bugfixes and QoL improvements from now on.</li>
    <li>If you go online with added slots, you take full responsibility on anything that happens to your Nintendo Switch or Nintendo Online account.</li>
    <li>We do not endorse going online with added slots and recommend not to. Slot spoofing is a work-in-progress and you should NOT trust it blindly, at least for the time being.</li>
</ul>"""

[[entries]]
section_title = "Donations"
contents = """
<p>As some of you may know, ARCropolis is a free modloader built on our spare time while trying to make a living on the side.</p>
<p>We would be very grateful if you could spare to make a donation to some of our contributors for their hard work!</p>
<p>If you'd like to make a donation, links are available at the following page: https://latest.arcropolis.com</p>
"""