# No idea if this will work
name: Build commit
on: [workflow_dispatch]
jobs:
  build:
    env:
      PLUGIN_NAME: arcropolis
    runs-on: ubuntu-latest
    container: 
      image: jugeeya/cargo-skyline:2.1.0-dkp
    steps:
    - name: Build ARCropolis and package it
      run: cargo skyline package --no-skyline
    - name: Upload package
      uses: actions/upload-artifact@v2
      with:
        name: ARCropolis
        path: target/release.zip
