name: Rust Build

on:
  push:
    branches: [ master ]
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install cargo-skyline
      run: cargo install --git https://github.com/jam1garner/cargo-skyline
    - name: Install rust-std-skyline-squashed
      run: cd .. && git clone https://github.com/jam1garner/rust-std-skyline-squashed && cd -
    - name: Attempt to build
      run: PATH=$PATH:/usr/share/rust/.rustup/toolchains/nightly-2020-04-10-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/bin cargo skyline build --release
# uncomment the build step below to build on every change to master.
#    - name: Update Release
#      env:
#          PLUGIN_NAME: 'libreplace.nro'  #  change this to the name of your plugin
#      uses: meeDamian/github-release@2.0
#      with:
#        token: ${{ secrets.GITHUB_TOKEN }}
#        prerelease: true
#        allow_override: true
#        gzip: false
#        tag: master
#        name: master
#        body: Build of ${{env.PLUGIN_NAME}} from master.
#        files: >
#          ./target/aarch64-skyline-switch/release/${{env.PLUGIN_NAME}}
